### PR TITLE
Add new workflow for items sync

### PR DESCRIPTION
**Pull request by dalejo96**
This is the test of the new workflow that helps us sync the items with the [Twilio Quest server repo](https://github.com/twilio/twilioquest-server)

For now we are using the directory: **"test/functions/views/items"**
That is not the real one, this is just to confirm the functionality of the action.
Later on, after confirming that all is working as expected, I will update the workflow to update the real items folder.

Thanks for checking.

### CODE REVIEW

**Comment by rmkubik** [comment]
Does this action have blanket permission to commit whatever it wants to the `twilioquest-server` repository?

**Comment by dalejo96** [comment]
> Does this `github-action-push-to-another-repository` action have blanket permission to commit whatever it wants to the `twilioquest-server` repository?

This action is going to commit just the `source-directory` to the `target-directory` from the source to the target repo. We established the connection using the SSH key that you helped me create the other day.

**Comment by rmkubik** [comment]
We are trusting the action to do what it says here though? If the action is compromised it would be able to commit arbitrary code. Is that correct? I'm not sure how we control access on the `SSH` key. It looks like an all around write permission though

**Comment by dalejo96** [comment]
Oh, I finally understand what do you mean :smile: 
I checked the action before choosing this one, they are now in version 1.5, it is well maintained and has the most stars of all the actions that copy directories from one repo to another. We can keep track of the action in case something is wrong.

**Comment by rmkubik** [comment]
Checked with some internal folks. If we're confident in the safety of the current action, we should pin our usage of the action to the current git commit SHA we want to use.

[This article](https://michaelheap.com/ensure-github-actions-pinned-sha/) talks about this in the "Why is it important?" section.

**Review by rmkubik — CHANGES_REQUESTED** [review]
Pin the 3rd party action to the specific git sha we want to use to ensure a future malicious update doesn't get automatic access to our code.

**Review by rmkubik — APPROVED** [review]
Looks good! This seems to work for what some internal security minded folks suggested for 3rd party actions.

I added a date to the comment next to the hash to hopefully remind us to keep this better up to date.

**Pull request merged**
