### PR TITLE
OSS Assets

### PR DESCRIPTION
**Pull request by kerrielake**
-Ele NPC +Icon (may update to add more animations)
-Tileset Update (pipes, windows, fridge, stove, food pantry, apple)

### CODE REVIEW

**Comment by rmkubik** [comment]
I just merged #26 with the other TwilioQuestTileset changes, like adding doors. 

I see this PR touches that file as well. We'll need to be sure the version of the tileset in this branch contains those changes as well.

**Comment by kerrielake** [comment]
Thanks for the heads up! In the future I'll make sure that all branches
containing the same file are up to date.

**Comment by rmkubik** [comment]
This PR touches `TwilioQuestTileset`. I just merged #28. Does this PR have the same version of `TwilioQuestTileset` in it? If so I can merge this in!

**Comment by kerrielake** [comment]
Yep! This branch also has the most recent version of the file.

**Review by rmkubik — APPROVED** [review]

**Pull request merged**
